# Generated by Django 5.1.5 on 2025-01-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('storehouse', '0002_initial'),
        ('task_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productionpath',
            name='id_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='productionpath',
            name='id_storehouse_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Наименование изделия'),
        ),
        migrations.AddField(
            model_name='task',
            name='id_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders', verbose_name='Номер заказа'),
        ),
        migrations.AddField(
            model_name='task',
            name='id_storehouse_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Наименование изделия'),
        ),
    ]
