# Generated by Django 5.1.4 on 2025-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contract',
            field=models.FileField(upload_to='contracts'),
        ),
    ]
