# Generated by Django 5.1.4 on 2025-01-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='contract',
            field=models.FileField(upload_to='contracts', verbose_name='Файл договора'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.clients', verbose_name='Клиент'),
        ),
    ]
