# Generated by Django 5.1.4 on 2025-01-09 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodObtaining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_obtaining', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_measurement', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storehouse_unit', models.CharField(max_length=150, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('id_method_obtaining', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.methodobtaining')),
                ('id_unit_measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement')),
            ],
        ),
        migrations.CreateModel(
            name='OwnProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storehouse_elements', models.ManyToManyField(related_name='own_production_elements', to='storehouse.storehouse')),
                ('id_storehouse_own_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse')),
            ],
        ),
        migrations.CreateModel(
            name='FinalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storehouse_elements', models.ManyToManyField(related_name='product_elements', to='storehouse.storehouse')),
                ('id_storehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_storehouse_assembly_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse')),
                ('id_storehouse_elements', models.ManyToManyField(related_name='assembly_unit_elements', to='storehouse.storehouse')),
            ],
        ),
    ]
