# Generated by Django 5.1.5 on 2025-01-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storehouse', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyunit',
            name='id_employee_position',
            field=models.ManyToManyField(related_name='assembly_unit_employee_position', to='users.employeeposition', verbose_name='Специализация исполнителя'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='id_employee_position',
            field=models.ManyToManyField(related_name='final_product_employee_position', to='users.employeeposition', verbose_name='Специализация исполнителя'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='id_employee_position',
            field=models.ManyToManyField(related_name='own_production_employee_position', to='users.employeeposition', verbose_name='Специализация исполнителя'),
        ),
        migrations.AddField(
            model_name='storehouse',
            name='id_method_obtaining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.methodobtaining', verbose_name='Спопоб получания'),
        ),
        migrations.AddField(
            model_name='storehouse',
            name='id_seller',
            field=models.ManyToManyField(blank=True, related_name='seller', to='storehouse.seller', verbose_name='Продавец'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='own_production_elements', to='storehouse.storehouse', verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='id_storehouse_own_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Элемент собственного производства'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='product_elements', to='storehouse.storehouse', verbose_name='Составные части изделия'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='id_storehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Изделие'),
        ),
        migrations.AddField(
            model_name='assemblyunit',
            name='id_storehouse_assembly_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Сборочная единица'),
        ),
        migrations.AddField(
            model_name='assemblyunit',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='assembly_unit_elements', to='storehouse.storehouse', verbose_name='Составные части сборочной единицы'),
        ),
        migrations.AddField(
            model_name='technologicalprocess',
            name='id_storehouse_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Элемент склада'),
        ),
        migrations.AddField(
            model_name='storehouse',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='assemblyunit',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
    ]
