# Generated by Django 5.1.4 on 2025-01-10 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0002_assemblyunit_created_at_assemblyunit_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='documentation/technological_process')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_storehouse_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse')),
            ],
        ),
    ]
