# Generated by Django 5.1.4 on 2025-01-10 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0003_documentation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documentation',
            new_name='TechnologicalProcess',
        ),
    ]
