# Generated by Django 5.1.4 on 2025-01-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0004_rename_documentation_technologicalprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=300, unique=True)),
                ('phone_number', models.IntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='storehouse',
            name='c1_article',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storehouse',
            name='id_seller',
            field=models.ManyToManyField(related_name='seller', to='storehouse.seller'),
        ),
    ]
