# Generated by Django 5.1.4 on 2025-01-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0005_seller_storehouse_c1_article_storehouse_id_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storehouse',
            name='id_seller',
            field=models.ManyToManyField(blank=True, related_name='seller', to='storehouse.seller'),
        ),
    ]
