# Generated by Django 5.1.4 on 2025-01-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0006_alter_storehouse_id_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='storehouse',
            name='storage_place',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
