# Generated by Django 5.1.4 on 2025-01-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0007_storehouse_storage_place_alter_seller_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodobtaining',
            name='method_obtaining',
            field=models.CharField(max_length=80, unique=True, verbose_name='Метод получения'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='почта продовца'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='Телефонный номер продовца'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт продовца'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='c1_article',
            field=models.IntegerField(blank=True, verbose_name='Артикул в 1С'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='storage_place',
            field=models.CharField(blank=True, max_length=150, verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='storehouse_unit',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='unitmeasurement',
            name='unit_measurement',
            field=models.CharField(max_length=20, unique=True, verbose_name='Мера измерения'),
        ),
    ]
