# Generated by Django 5.1.4 on 2025-01-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0008_alter_methodobtaining_method_obtaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologicalprocess',
            name='pdf_file',
            field=models.FileField(upload_to='technological_process'),
        ),
    ]
