# Generated by Django 5.1.4 on 2025-01-18 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0009_alter_technologicalprocess_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyunit',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='assemblyunit',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='finalproduct',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AddField(
            model_name='ownproduction',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='id_storehouse_assembly_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Сборочная единица'),
        ),
        migrations.AlterField(
            model_name='assemblyunit',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='assembly_unit_elements', to='storehouse.storehouse', verbose_name='Составные части сборочной единицы'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='product_elements', to='storehouse.storehouse', verbose_name='Составные части изделия'),
        ),
        migrations.AlterField(
            model_name='finalproduct',
            name='id_storehouse_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Изделие'),
        ),
        migrations.AlterField(
            model_name='ownproduction',
            name='id_storehouse_elements',
            field=models.ManyToManyField(related_name='own_production_elements', to='storehouse.storehouse', verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='ownproduction',
            name='id_storehouse_own_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Элемент собственного производства'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='id_method_obtaining',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.methodobtaining', verbose_name='Спопоб получания'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='id_seller',
            field=models.ManyToManyField(blank=True, related_name='seller', to='storehouse.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='storehouse',
            name='id_unit_measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storehouse.unitmeasurement', verbose_name='Мера измерения'),
        ),
        migrations.AlterField(
            model_name='technologicalprocess',
            name='id_storehouse_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storehouse.storehouse', verbose_name='Элемент склада'),
        ),
        migrations.AlterField(
            model_name='technologicalprocess',
            name='pdf_file',
            field=models.FileField(upload_to='technological_process', verbose_name='Файл с технической документацией'),
        ),
    ]
