# Generated by Django 5.1.4 on 2025-01-18 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storehouse', '0010_assemblyunit_id_unit_measurement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assemblyunit',
            options={'verbose_name': 'Сборочная единица', 'verbose_name_plural': 'Сборочные единицы'},
        ),
        migrations.AlterModelOptions(
            name='finalproduct',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
        migrations.AlterModelOptions(
            name='methodobtaining',
            options={'verbose_name': 'Метод получения', 'verbose_name_plural': 'Метод получения'},
        ),
        migrations.AlterModelOptions(
            name='ownproduction',
            options={'verbose_name': 'Элемент собственного производства', 'verbose_name_plural': 'Элементы собственного производства'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы'},
        ),
        migrations.AlterModelOptions(
            name='storehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterModelOptions(
            name='technologicalprocess',
            options={'verbose_name': 'Техническая документация ', 'verbose_name_plural': 'Техническая документация'},
        ),
        migrations.AlterModelOptions(
            name='unitmeasurement',
            options={'verbose_name': 'Количество', 'verbose_name_plural': 'Количество'},
        ),
    ]
