# Generated by Django 5.1.4 on 2025-01-09 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_employee_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeposition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
