# Generated by Django 5.1.4 on 2025-01-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role_naame',
            new_name='role_name',
        ),
    ]
