# Generated by Django 5.1.4 on 2025-01-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_role_naame_role_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(related_name='role', to='users.role'),
        ),
    ]
