# Generated by Django 5.1.4 on 2025-01-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employee_email_alter_employee_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='employees', to='users.employeeposition', verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(related_name='role', to='users.role', verbose_name='Должность'),
        ),
    ]
